### ISSUE TITLE
LLaMA Factory + GLM4 微调最佳实践

### ISSUE THREAD

**Issue by hiyouga** [THUDM/GLM-4#26]
LLaMA Factory 支持了 GLM-4-9B 和 GLM-4-9B-Chat 模型的**指令微调、RLHF、DPO 和 SimPO** 等优化方法

https://github.com/hiyouga/LLaMA-Factory/blob/main/README_zh.md

### 指令微调

```bash
CUDA_VISIBLE_DEVICES=0,1 HF_ENDPOINT=https://hf-mirror.com llamafactory-cli train sft.yaml
```

`sft.yaml` 文件内容：

```yaml
### model
model_name_or_path: THUDM/glm-4-9b-chat

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: identity,alpaca_en_demo,alpaca_zh_demo
template: glm4
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/glm4-sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500
```

![sft](https://github.com/THUDM/GLM-4/assets/16256802/f023049f-36ed-4243-b58d-006595695c80)

### 多卡推理

```bash
CUDA_VISIBLE_DEVICES=0,1 HF_ENDPOINT=https://hf-mirror.com llamafactory-cli chat \
    --model_name_or_path THUDM/glm-4-9b-chat \
    --adapter_name_or_path saves/glm4-sft \
    --template glm4 \
    --finetuning_type lora
```

### 资源使用

LoRA: ~20GB
QLoRA: ~10GB
半精度推理：~18GB
4-bit 推理：~7GB

![vram](https://github.com/THUDM/GLM-4/assets/16256802/72efd736-baab-42e1-84f8-06c6ce8b07ce)
